# config/application.yml
defaults: &defaults
  
  dictionary_api:
    url: 'http://ec2-23-23-23-199.compute-1.amazonaws.com/api.php?word='
  
  pubnub:
      publish_key: 'pub-c-58c17d88-fbdf-4b60-87f8-94f63b5a4ee3'
      subscribe_key: 'sub-c-1649aff2-81cf-11e2-b64e-12313f022c90'
    

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults